include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    non_constant_identifier_names: ignore
    camel_case_types: ignore
