name: my_tube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  image_picker: ^1.0.4
  path: ^1.8.3
  mime: ^1.0.4
  file_picker: ^6.1.1
  video_player: ^2.5.0
  video_player_win: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
